import Link from "next/link"
import { FileText, Filter, Plus, Search, Upload } from "lucide-react"
import { AppShell } from "@/components/app-shell"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { demoContracts, pageDescriptions } from "@/lib/domain"

export default function ContractsPage() { return <AppShell><div className="flex flex-col gap-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Workspace / Contracts</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Contracts</h1><p className="mt-2 text-sm text-muted-foreground">{pageDescriptions.contracts}</p></div><Button><Upload data-icon="inline-start" /> Upload contract</Button></div><Card><CardContent className="flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search contracts" aria-label="Search contracts" /></div><Button variant="outline"><Filter data-icon="inline-start" /> Filters</Button><Button variant="outline">Sort: Recently updated</Button></CardContent></Card><Card><CardHeader><CardTitle>All contracts</CardTitle><CardDescription>Demo records are labeled in this preview. Production documents will be scoped to your organization.</CardDescription></CardHeader><CardContent className="px-0"><div className="flex flex-col">{demoContracts.map((contract) => <Link key={contract.id} href={`/dashboard/contracts/${contract.id}`} className="flex flex-col gap-3 border-t border-border px-6 py-4 transition-colors hover:bg-muted/35 sm:flex-row sm:items-center"><div className="grid size-10 shrink-0 place-items-center rounded-lg bg-muted"><FileText className="size-5 text-muted-foreground" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{contract.title}</p><p className="mt-1 text-xs text-muted-foreground">{contract.fileType} · {contract.pages} pages · Updated {contract.updatedAt}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{contract.status}</Badge>{contract.riskLevel && <Badge variant={contract.riskLevel === "High" ? "destructive" : "secondary"}>{contract.riskLevel} risk</Badge>}</div></Link>)}<div className="border-t border-border px-6 py-10 text-center"><div className="mx-auto grid size-10 place-items-center rounded-full bg-muted"><Plus className="size-5 text-muted-foreground" /></div><p className="mt-3 text-sm font-medium">Upload another contract</p><p className="mt-1 text-sm text-muted-foreground">PDF and DOCX files up to 25 MB are supported.</p><Button className="mt-4" variant="outline"><Upload data-icon="inline-start" /> Choose file</Button></div></div></CardContent></Card></div></AppShell> }
